---
title: やまだけんいち
author: Kenichi Yamada
email: ''
description: Webアプリ開発が大好きな学生、やまだけんいちのホームページです。
baseurl: https://r-40021.github.io/
url: https://r-40021.github.io/
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
