---
title: やまだアプリ工房
author: Frog
email: ''
description: Webアプリを開発している、やまだアプリ工房です。
baseurl: ''
url: https://www.frogapp.net/
defaults:
- scope:
    path: "/google1e027241d812a8ed.html"
  values:
    sitemap: false
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
- jekyll-sitemap
