---
title: カエルアプリ工房
author: Frog
email: ''
description: ウェブアプリを開発している、カエルアプリ工房です。
baseurl: ''
url: https://www.frogapp.net/
defaults:
- scope:
    path: "/google1e027241d812a8ed.html"
  values:
    sitemap: false
- scope:
    path: ''
  values:
    layout: default
# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []
plugins:
- jekyll-feed
- jekyll-menus
- jekyll-sitemap
